"""Create tweets table1

Revision ID: 732dfb2e9d54
Revises: 751255adbba5
Create Date: 2022-01-20 16:19:51.858022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '732dfb2e9d54'
down_revision = '751255adbba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=280), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tweets')
    # ### end Alembic commands ###
